### ISSUE TITLE
backup && restore can't work

### ISSUE THREAD

**Issue by fcying** [jim3ma/docker-leanote#4]
![image](https://user-images.githubusercontent.com/106934/43073453-40ad011e-8eac-11e8-881c-a15941e28996.png)

**Comment by jim3ma** [comment]
You must  set correct info in `Mongodb Tool Configuration` like this:

mongodump path:

```
/usr/bin/mongodump
```

mongorestore path:

```
/usr/bin/mongorestore
```

**Comment by fcying** [comment]
after set `mongodump`   && `mongorestore`  path, it can work now, thanks
